sudo: required

language: nodejs

services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  # Tagging
  - docker tag udagram-api-feed 237656813866/udagram-api-feed:v1
  - docker tag udagram-api-user 237656813866/udagram-api-user:v1
  - docker tag udagram-frontend 237656813866/udagram-frontend:v1
  - docker tag reverseproxy 237656813866/reverseproxy:v1

script:
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 237656813866/udagram-api-feed:v1
  - docker push 237656813866/udagram-api-user:v1
  - docker push 237656813866/udagram-frontend:v1
  - docker push 237656813866/reverseproxy:v1

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub"; fi
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - export REPO=jayjohnson/springxd-base
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO